---
- name: get name of hosts from IP addresses on virbr0 network
  hosts: localhost
  connection: local 
  tasks:
    # Simple check for ip's connected to the virbr0 network
    - name: check ip's
      shell: arp -n -i virbr0 |tail -n +2 |  awk '{print $1}'
    #      shell: nmap -n -sn 192.168.122.* -oG - | awk '/Up$/{print $2}'
      register: active_nodes

    - name: debug the nodes
      debug:
        msg: "{{ active_nodes.stdout_lines }}"
        verbosity: 3   
    - name: step nodes
      debug:
        msg: "{{ item }}"
        verbosity: 3
      loop: "{{ active_nodes.stdout_lines }}"
        

    - name: Add hosts to the group DynamicHosts
      add_host:
        hostname: "{{ item }}"
        groups:
          DynamicHosts
      loop: "{{ active_nodes.stdout_lines }}"
 
- hosts: DynamicHosts
  become: yes
  gather_facts: yes
  tasks:

    - name: setup inventory
      setup: ~


    - name: get hostname
      command: hostname -f
      register: thenode_name
      
    - name: hostnames
      debug:
         msg: "{{ thenode_name }}"
         verbosity: 3  
#    - debug:
#        var: hostvars


    - name: Checking name
      debug:
        msg: "{{ ansible_fqdn }}"
        verbosity: 3

    - name: create hosts_file
      template:
        src: templates/hosts.j2 
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        force: yes
      delegate_to: "{{ delegate_host | default('control') }}"
      #become: no



    - name: Create ansible inventory files
      template:
        src: templates/inventory.j2 
        dest: /home/admin/ansible/inventory
        owner: admin
        group: admin 
      delegate_to: "{{ delegate_host | default('control') }}"

      